### ISSUE TITLE
Can not start launch configuration

### ISSUE THREAD

**Issue by hhoellerl** [tsvetan-stoyanov/launchpi#11]
Hi,
I recently have installed launchpi. Thank you for providing this.

No problems running progams remote, but debugging does not work, at least on my
computer/raspberryPi.

I always get following Eclipse error:

Can not start launch configuration
Failed to connect to remote VM. Connection refused. 

I think server does not run yet when eclipse tries to connect, i.e.
From my perspective it looks like whether eclipse error already appears before
"Listening for transport dt_socket at address: 4000" is printed in console.

Is there a way to give remote raspberry process a little more time, before eclipse
tries to connect?

Thanks and ciao,
Harry

**Comment by rudderfeet** [comment]
I've encountered the same thing here.  I can use Run but not Debug.

**Comment by tsvetan-stoyanov** [comment]
Fixed.
