### ISSUE TITLE
Project that depends on other project throws NullPointerException

### ISSUE THREAD

**Issue by akatran** [tsvetan-stoyanov/launchpi#12]
I have a program that I want to run on Raspberry PI with LaunchPi but
when I add the other program into build path the Eclipse throws a message with the following text:
Can not start launch configuration
java.lang.NullPointerException

Any Ideas of how can I run it on Pi;

**Comment by tsvetan-stoyanov** [comment]
Can you share more details on the project's classpath - maybe the .classpath file? Is this java project to java project dependency?
It might be an issue similar to #10 

10x
Tsvetan

**Comment by akatran** [comment]
I build two project simultaneously and lets say that project A is needed for project B.
If I put project A in required projects of project B then I got the null poiner exception.
The classfile contains :
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry combineaccessrules="false" exported="true" kind="src" path="/halfDuplexModbus"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="lib" path="libs/jssc.jar"/>
	<classpathentry kind="lib" path="libs/pi4j-core.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

In order to include project A I add the class folder only in project B libraries (only this is working).

 Thank you for your time!

**Comment by akatran** [comment]
I found out that I cannot just copy-paste the content of the file so I include it bellow adding a space after each "<" at the beginning

< classpath>
	< classpathentry combineaccessrules="false" exported="true" kind="src" path="/halfDuplexModbus"/>
	< classpathentry kind="src" path="src"/>
	< classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	< classpathentry kind="lib" path="libs/jssc.jar"/>
	< classpathentry kind="lib" path="libs/pi4j-core.jar"/>
	< classpathentry kind="output" path="bin"/>
< /classpath>

**Comment by tsvetan-stoyanov** [comment]
Please try with the newest version. Dependencies to other projects should be supported now.

**Comment by tsvetan-stoyanov** [comment]
Fixed.
