### ISSUE TITLE
masqued directory on PI

### ISSUE THREAD

**Issue by JojoLeNantais** [tsvetan-stoyanov/launchpi#15]
Hi,
the eclipse project is copied on the PI but in a masqued directory begining with a "."
why ?
thanks for this good work.

**Comment by tsvetan-stoyanov** [comment]
The hidden directory is supposed to be used only by the launchpi plugin during run and debug sessions. It's not intended to be used as a place to actually install any application. Hiding the directory signals the user that it is not under her control.

10x
Tsvetan
