### ISSUE TITLE
Delete a ssh ip from the list... Or alternatively change the user for the ssh access

### ISSUE THREAD

**Issue by marioconforti** [tsvetan-stoyanov/launchpi#19]
I mistyped the pi user in the configuration, and now i cannot add a new ip from the list deleteing the old one or changing the user from the ssh log in interface

thanks

**Comment by tsvetan-stoyanov** [comment]
Switch to the "Remote System Explorer" perspective and select the host in the "Remote Systems" view. In the "Properties" view you will see a property named "Default User ID" which have to be edited. Once the user id is fixed, re-launch the application.

![untitled](https://cloud.githubusercontent.com/assets/6024682/8217194/94a4dca4-1544-11e5-90b9-f8b7f05860bd.png)

**Comment by marioconforti** [comment]
Thank you!
