### ISSUE TITLE
problem with long filenames

### ISSUE THREAD

**Issue by timduente** [tsvetan-stoyanov/launchpi#20]
Hi,

first you created a very nice plugin.

I have some problems with long filenames:

Example error message:

Can not start launch configuration
file name 'classes/org/scenariotools/sdl/runtime/services/ConfigurationGrammarAccess$ConfigurationElements.class' is too long ( > 100 bytes)

Do you have an idea to solve this problem?

Best regards

Tim

**Comment by tsvetan-stoyanov** [comment]
Fixed.
