### ISSUE TITLE
Kudos to LaunchPI from CodeRasPIde : IDE for PI4J & RasberryPI

### ISSUE THREAD

**Issue by cmalai** [tsvetan-stoyanov/launchpi#21]
Hi There

Hope you doing good. Awesome work with LaunchPI. Impressed and you saved us a lot of time too. Thank you for that. CodeRasPIde is an IDE for RasberryPI created in the last week. We hit upon your LaunchPI when were looking at options to Remote Deploy from Java and we successfully have integrated your plugin into our IDE. CodeRasPIde is to be released to the RasberryPI Community tomorrow @ Eclipse Con, Europe 2015 as part of our showcasing.

I thot i should appreciate your work and I would send out the Download Link to you once it is up and running tomorrow for your reviews and also the github account for you fork out code.

You may read about it : http://eclipseo.blogspot.in/2015/11/1st-preview-screenshot-of-code-raspide.html

Thanks Once again for LaunchPI.

**Comment by tsvetan-stoyanov** [comment]
Hey that's really great. I'll give it a try.
I'm happy that LaunchPI is useful for you and will appreciate any future contributions from your side.

Keep on going!
