### ISSUE TITLE
Eclipse Console screen put a extra space after 80 caracters. 

### ISSUE THREAD

**Issue by interdigitec** [tsvetan-stoyanov/launchpi#8]
Hi,
Great job. I made some test and I thing I will adopt this plugin :-)
Just one little things, The console output shows an extra space after 80 caracters.
It is probably because the terminal is configured with a width of 80 caracters and the \n is replaced in the eclipse console by a space.
Again, great job.

BR
Reinhard

**Comment by nkolban** [comment]
+1 ... I was also about to raise this as an issue ... oh oh ... it looks like its been over a year since any action.

**Comment by tsvetan-stoyanov** [comment]
Fixed.
